[package]
name = "ac_2022_01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent_of_code_util = {path = "../advent_of_code_util"}
itertools = "0.10.2"
