[package]
name = "ac_2023_12"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent_of_code_util = {path = "../advent_of_code_util"}
itertools.workspace = true
